#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io
  - wireguard
  - ufw

write_files:
  - path: /etc/wireguard/wg0.conf
    content: |
      [Interface]
      PrivateKey = ${vpn_key}
      Address = ${vpn_address}/24
      
      [Peer]
      PublicKey = ${panel_public_key}
      Endpoint = ${panel_endpoint}
      AllowedIPs = ${vpn_network}
      PersistentKeepalive = 25
    permissions: '0600'
    
  - path: /root/wings-setup.sh
    content: |
      #!/bin/bash
      # Configure firewall
      ufw allow 22/tcp
      ufw allow 8080/tcp
      ufw allow 2022/tcp
      ufw allow 27015:27020/tcp
      ufw allow 27015:27020/udp
      ufw allow 51820/udp
      ufw --force enable
      
      # Setup WireGuard if enabled
      %{ if enable_vpn ~}
      wg-quick up wg0
      systemctl enable wg-quick@wg0
      %{ endif ~}
      
      # Configure Docker
      systemctl enable --now docker
    permissions: '0755'

runcmd:
  - bash /root/wings-setup.sh